// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dncasbin.Migrations
{
    [DbContext(typeof(CasbinDatabase))]
    [Migration("20250914193359_Casbin")]
    partial class Casbin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("casbin")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Casbin.Persist.Adapter.EFCore.Entities.EFCorePersistPolicy<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("ptype");

                    b.Property<string>("Value1")
                        .HasColumnType("text")
                        .HasColumnName("v0");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("v1");

                    b.Property<string>("Value3")
                        .HasColumnType("text")
                        .HasColumnName("v2");

                    b.Property<string>("Value4")
                        .HasColumnType("text")
                        .HasColumnName("v3");

                    b.Property<string>("Value5")
                        .HasColumnType("text")
                        .HasColumnName("v4");

                    b.Property<string>("Value6")
                        .HasColumnType("text")
                        .HasColumnName("v5");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Value1");

                    b.HasIndex("Value2");

                    b.HasIndex("Value3");

                    b.HasIndex("Value4");

                    b.HasIndex("Value5");

                    b.HasIndex("Value6");

                    b.ToTable("casbin_rule", "casbin");
                });
#pragma warning restore 612, 618
        }
    }
}
